stages:
  - validate_format
  - validate_types
  - build


default:
  image: node:18

# Checking format in frontend
frontend_format:
  stage: validate_format
  script:
    - cd frontend && npm install
    - cd frontend && npm run lint-check
    - cd frontend && npm run format-check

# Validate typescript in frontend
frontend_typescript:
  stage: validate_types
  script:
    - cd frontend && npm install
    - cd frontend && npm run type-check

# Build frontend
frontend_build:
  stage: build
  script:
    - cd frontend && npm install
    - cd frontend && npm run build-only