
services:
  frontend:
    build: backend
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=change_me
      - DJANGO_ALLOWED_HOSTS=localhost
      - CSRF_TRUSTED_ORIGINS=http://lulhost:8080
      - RN_KEY=$RN_KEY
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=urbs
      - SQL_USER=urbs
      - SQL_PASSWORD=urbs
      - SQL_HOST=db
      - SQL_PORT=5432
    depends_on:
      - db
    command: gunicorn backendurbs.wsgi:application --bind 0.0.0.0:8000

  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=urbs
      - POSTGRES_PASSWORD=urbs
      - POSTGRES_DB=urbs

#  reverse-proxy:
#    image: nginx:alpine
#    container_name: reverse-proxy
#    ports:
#      - "9000:9000"
#    volumes:
#      - /proxy/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  postgres_data: