
services:
  backend:
    build: backend
    container_name: weburbs-backend
    environment:
      - SECRET_KEY=change_me
      - URBS_CALLBACK=http://backend:9000
      - URBS=http://optimizer:5000
      - DJANGO_ALLOWED_HOSTS=localhost
      - ORIGINS=http://localhost:9000
      - RN_KEY=$RN_KEY
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=urbs
      - SQL_USER=urbs
      - SQL_PASSWORD=urbs
      - SQL_HOST=db
      - SQL_PORT=5432
    depends_on:
      - db
    networks:
      - urbs

  db:
    image: postgres:17
    container_name: weburbs-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=urbs
      - POSTGRES_PASSWORD=urbs
      - POSTGRES_DB=urbs
    networks:
      - urbs

  frontend:
    build: frontend
    container_name: weburbs-frontend
    environment:
      - POSTGRES_USER=urbs
      - VUE_APP_API_URL=http://localhost:9000
    networks:
      - urbs

  reverse-proxy:
    image: nginx:alpine
    container_name: weburbs-proxy
    ports:
      - "9000:9000"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - urbs

volumes:
  postgres_data:
networks:
  urbs:
    driver: bridge
