
services:
  backend:
    build: backend
    environment:
      - SECRET_KEY=change_me
      - DJANGO_ALLOWED_HOSTS=localhost
      - CSRF_TRUSTED_ORIGINS=http://localhost:9000
      - RN_KEY=$RN_KEY
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=urbs
      - SQL_USER=urbs
      - SQL_PASSWORD=urbs
      - SQL_HOST=db
      - SQL_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=urbs
      - POSTGRES_PASSWORD=urbs
      - POSTGRES_DB=urbs

  frontend:
    build: frontend
    environment:
      - POSTGRES_USER=urbs
      - VUE_APP_API_URL=http://localhost:9000

  reverse-proxy:
    image: nginx:alpine
    container_name: reverse-proxy
    ports:
      - "9000:9000"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  postgres_data: